### ISSUE TITLE
I can agree multiple times with a tag, the counter keeps increasing

### ISSUE THREAD

**Issue by r03ert0** [OpenNeuroLab/brainspell-neo#27]
I have up-voted like 5 times the Magnetic Resonance Imaging tag here:
http://brainspell.herokuapp.com/view-article?id=16584892

**Comment by neelsomani** [comment]
Fixed with latest commit. Since I changed the database structure that we use to represent a vote, that same article (and any other articles previously voted on) might throw an error. At some point we'll have to switch out our current test database with a fresh copy. But you can test out the voting on a different article, and it should work.
