### ISSUE TITLE
Prompt user for a reason to exclude an article from a collection

### ISSUE THREAD

**Issue by Sharabesh** [OpenNeuroLab/brainspell-neo#59]
On the UI, create a prompt asking for a reason when a user excludes an article from a collection. Make necessary backend changes.

**Comment by akeshavan** [comment]
Done!

<img width="1044" alt="screenshot 2018-04-18 16 12 39" src="https://user-images.githubusercontent.com/972008/38962703-61c75572-4323-11e8-8536-9a2cc0ecd8a9.png">

**Comment by akeshavan** [comment]
Whoops, wrong issue. lol

**Comment by akeshavan** [comment]
Ok, now its really done: 

once added, you see this
<img width="264" alt="screenshot 2018-04-18 16 38 56" src="https://user-images.githubusercontent.com/972008/38963505-268dc370-4327-11e8-82ce-25fbe84e3bd4.png">

once you type in a reason, the button is enabled
<img width="229" alt="screenshot 2018-04-18 16 39 10" src="https://user-images.githubusercontent.com/972008/38963504-2677a018-4327-11e8-97c2-ab99173e6ac2.png">

@neelsomani @Sharabesh i'll need an endpoint to feed this through. We'll probably want to save this info in the github, since its user specific
